apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifcations
  name: notifcations
spec:
  ports:
    - name: 'tcp'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: notifcations
  type: ClusterIP
